"""budget: planned items, balance checks, spendable pots

Planned items feed the forecast of the next salary cycles; a balance check is the
real balance of a bank/wallet account typed between statements; `spendable` marks
the savings pots the budget may count as a reserve.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 12:51:23.979251
"""

from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_checks_account_id'), 'balance_checks', ['account_id'], unique=False)
    op.create_table('planned_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('repeat_months', sa.Integer(), nullable=True),
    sa.Column('until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='planned', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('spendable', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'spendable')
    op.drop_table('planned_items')
    op.drop_index(op.f('ix_balance_checks_account_id'), table_name='balance_checks')
    op.drop_table('balance_checks')
    # ### end Alembic commands ###
